'use client';

import React, { useState, useEffect, useRef, useCallback } from 'react';
import dynamic from 'next/dynamic';
import { HTMLCanvasEpsonPrinter } from '../html-canvas-printer-exact';
import { executeJavaScriptInterpreter } from '../lib/js-interpreter-executor';
import type { EpsonPrinter, Alignment, TextSize, BarcodeType } from '../interfaces/epson-printer-exact';
import type { Order } from '../interfaces/order';

// Dynamically import the JS editor to avoid SSR issues
const SimpleJSEditor = dynamic(
  () => import('./SimpleJSEditor').then(mod => mod.SimpleJSEditor),
  { 
    ssr: false,
    loading: () => (
      <div className="w-full h-96 bg-black border border-gray-600 rounded-lg flex items-center justify-center">
        <div className="text-green-400">Loading JavaScript Editor...</div>
      </div>
    )
  }
);

interface ReceiptPreviewProps {
  jsonDsl: string;
}

type SubTab = 'json' | 'order' | 'api' | 'interpreter' | 'receipt';

const DEFAULT_JS_INTERPRETER = `function interpret(jsonString, printer, order) {
  // Parse the JSON DSL generated by Visual Receipt Designer
  const json = JSON.parse(jsonString);
  
  // Enhanced dynamic field resolver (matches Kotlin interpreter)
  function resolveDynamicField(field, order) {
    if (!order) {
      // Default values when no order data is available
      switch (field) {
        case '{store_name}': return 'BYTE BURGERS';
        case '{store_address}': return '123 Tech Ave, Silicon Valley';
        case '{store_number}': return '001';
        case '{cashier_name}': return 'Cashier';
        case '{timestamp}': return new Date().toLocaleString();
        case '{order_number}': return 'ORD-001234';
        case '{order_id}': return 'A-0001';
        case '{subtotal}': return '$25.99';
        case '{tax}': return '$2.34';
        case '{total}': return '$28.33';
        case '{item_list}': return '1x Sample Item - $8.99';
        default: return field; // Return as-is if not recognized
      }
    }
    
    // Resolve from actual order data
    switch (field) {
      case '{store_name}': return order.storeName || 'BYTE BURGERS';
      case '{store_address}': return '123 Tech Ave, Silicon Valley';
      case '{store_number}': return order.storeNumber || '001';
      case '{cashier_name}': return order.customerInfo?.name || 'Cashier';
      case '{timestamp}': return new Date(order.timestamp || Date.now()).toLocaleString();
      case '{order_number}': return order.orderId || 'ORD-001234';
      case '{order_id}': return order.orderId || 'A-0001';
      case '{subtotal}': return '$' + (order.subtotal || 0).toFixed(2);
      case '{tax}': return '$' + (order.taxAmount || 0).toFixed(2);
      case '{total}': return '$' + (order.totalAmount || 0).toFixed(2);
      case '{item_list}': return formatItemList(order.items || [], order.itemPromotions || []);
      case '{customer_name}': return order.customerInfo?.name || '';
      case '{customer_id}': return order.customerInfo?.customerId || '';
      case '{loyalty_points}': return (order.customerInfo?.loyaltyPoints || '').toString();
      case '{member_status}': return order.customerInfo?.memberStatus || '';
      case '{payment_method}': return order.paymentMethod || '';
      case '{table_number}': return order.tableInfo?.tableNumber || '';
      case '{server_name}': return order.tableInfo?.serverName || '';
      case '{guest_count}': return (order.tableInfo?.guestCount || '').toString();
      default: return field; // Return as-is if not recognized
    }
  }
  
  // Format item list with quantities, names, and prices
  function formatItemList(items, promotions) {
    if (!items || items.length === 0) {
      return 'No items';
    }
    
    let itemText = '';
    items.forEach(item => {
      itemText += \`\${item.quantity}x \${item.name}\`;
      
      // Add modifiers if present
      if (item.modifiers && item.modifiers.length > 0) {
        itemText += \` (\${item.modifiers.join(', ')})\`;
      }
      
      itemText += \` - $\${item.totalPrice.toFixed(2)}\`;
      
      // Check for item-specific promotions
      const itemPromo = promotions.find(p => p.itemSku === item.sku);
      if (itemPromo) {
        itemText += \`\\n  PROMO: \${itemPromo.promotionName} -$\${itemPromo.discountAmount.toFixed(2)}\`;
      }
      
      itemText += '\\n';
    });
    
    return itemText.trim();
  }
  
  // Process each element in the JSON DSL
  if (json.elements && Array.isArray(json.elements)) {
    json.elements.forEach(element => {
      try {
        switch(element.type) {
          case 'text':
            // Print text with optional styling
            const text = element.content || '';
            if (element.style) {
              // Convert style to match EpsonPrinter format
              const style = {
                bold: element.style.bold || false,
                underline: element.style.underline || false,
                size: element.style.size || 'NORMAL'
              };
              printer.addText(text, style);
            } else {
              printer.addText(text);
            }
            break;
            
          case 'dynamic':
            // Resolve dynamic field and print
            const field = element.field || '';
            const value = resolveDynamicField(field, order);
            printer.addText(value);
            break;
            
          case 'divider':
            // Print horizontal line separator
            printer.addText('-'.repeat(48));
            printer.addFeedLine(1);
            break;
            
          case 'feed':
            // Add blank lines for spacing
            const lines = element.lines || 1;
            printer.addFeedLine(lines);
            break;
            
          case 'barcode':
            // Print barcode
            const barcodeData = element.data || '';
            const barcodeType = element.barcodeType || 'CODE39';
            const barcodeOptions = {
              width: 'MEDIUM',
              height: 50,
              hri: true
            };
            printer.addBarcode(barcodeData, barcodeType, barcodeOptions);
            break;
            
          case 'qrcode':
            // Print QR code
            const qrData = element.data || '';
            const qrOptions = {
              size: 3,
              errorCorrection: 'M'
            };
            printer.addQRCode(qrData, qrOptions);
            break;
            
          case 'image':
            // Print image (base64 encoded)
            const imageData = element.imageData || '';
            if (imageData) {
              const imageOptions = {
                width: 384,
                alignment: 'CENTER'
              };
              printer.addImage(imageData, imageOptions);
            }
            break;
            
          // Legacy compatibility for old format
          case 'align':
            printer.addTextAlign(element.alignment || 'LEFT');
            break;
            
          case 'feedLine':
            printer.addFeedLine(element.lines || 1);
            break;
            
          case 'cutPaper':
            printer.cutPaper();
            break;
            
          case 'items_list':
            // Legacy support - print item list directly
            if (order && order.items && order.items.length > 0) {
              const itemListText = formatItemList(order.items, order.itemPromotions || []);
              printer.addText(itemListText);
            } else {
              printer.addText('(No items)');
            }
            break;
            
          default:
            console.warn(\`Unknown element type: \${element.type}\`);
        }
      } catch (err) {
        console.error(\`Error processing element \${element.type}:\`, err);
        printer.addText(\`[Error in \${element.type} element]\`);
      }
    });
  }
  
  // Always cut paper at the end if not already done
  const lastElement = json.elements && json.elements[json.elements.length - 1];
  if (!lastElement || lastElement.type !== 'cutPaper') {
    printer.cutPaper();
  }
}`;

const DEFAULT_ORDER: Order = {
  // Basic fields (Round 1+)
  orderId: "A-0042",
  storeNumber: "001",
  storeName: "BYTE BURGERS",
  timestamp: Date.now(),
  
  // Items array with all optional fields
  items: [
    {
      name: "Classic Cheeseburger",
      quantity: 2,
      unitPrice: 8.99,
      totalPrice: 17.98,
      sku: "BURG-001",
      category: "BURGERS",
      modifiers: ["Medium Rare", "Extra Cheese"]
    },
    {
      name: "Crispy Fries",
      quantity: 1,
      unitPrice: 3.99,
      totalPrice: 3.99,
      sku: "SIDE-002",
      category: "SIDES"
    },
    {
      name: "Cola",
      quantity: 2,
      unitPrice: 2.99,
      totalPrice: 5.98,
      sku: "DRINK-003",
      category: "BEVERAGES"
    }
  ],
  
  // Totals (pre-calculated)
  subtotal: 27.95,
  taxRate: 0.08,
  taxAmount: 2.24,
  totalAmount: 30.19,
  
  // Optional fields for advanced rounds
  paymentMethod: "VISA ****1234",
  
  // Round 2+ Promotions
  itemPromotions: [
    {
      itemSku: "BURG-001",
      promotionName: "Burger Tuesday - 10% Off",
      discountAmount: 1.80
    }
  ],
  orderPromotions: [
    {
      promotionName: "Lunch Special",
      discountAmount: 2.00,
      promotionType: "FIXED"
    }
  ],
  
  // Round 3+ Customer Info
  customerInfo: {
    customerId: "CUST-8826",
    name: "John Doe",
    memberStatus: "GOLD",
    loyaltyPoints: 1247,
    memberSince: "2019-03-15"
  },
  
  // Round 5+ Split Payment & Table Info
  splitPayments: [
    {
      payerName: "Alice Chen",
      amount: 15.10,
      method: "VISA ****7823",
      tip: 3.00,
      items: ["Classic Cheeseburger", "Cola"]
    },
    {
      payerName: "Bob Smith",
      amount: 15.09,
      method: "MASTERCARD ****4567",
      tip: 3.00,
      items: ["Classic Cheeseburger", "Crispy Fries", "Cola"]
    }
  ],
  tableInfo: {
    tableNumber: "12",
    serverName: "Jennifer K.",
    guestCount: 2,
    serviceRating: 5
  }
};

export const ReceiptPreview: React.FC<ReceiptPreviewProps> = ({ jsonDsl }) => {
  const [activeSubTab, setActiveSubTab] = useState<SubTab>('json');
  const [jsCode, setJsCode] = useState(DEFAULT_JS_INTERPRETER);
  const [error, setError] = useState<string | null>(null);
  const [isRendering, setIsRendering] = useState(false);
  
  // Default example JSON for the Preview tab (matches Visual Receipt Designer format)
  const DEFAULT_PREVIEW_JSON = JSON.stringify({
    elements: [
      {
        type: "text",
        content: "BYTE BURGERS",
        style: { bold: true, size: "XLARGE" }
      },
      {
        type: "text",
        content: "123 Main Street"
      },
      {
        type: "divider"
      },
      {
        type: "dynamic",
        field: "{timestamp}"
      },
      {
        type: "feed",
        lines: 1
      },
      {
        type: "text",
        content: "Order #: "
      },
      {
        type: "dynamic",
        field: "{order_number}"
      },
      {
        type: "feed",
        lines: 2
      },
      {
        type: "dynamic",
        field: "{item_list}"
      },
      {
        type: "divider"
      },
      {
        type: "text",
        content: "Subtotal: "
      },
      {
        type: "dynamic",
        field: "{subtotal}"
      },
      {
        type: "feed",
        lines: 1
      },
      {
        type: "text",
        content: "Tax: "
      },
      {
        type: "dynamic",
        field: "{tax}"
      },
      {
        type: "feed",
        lines: 1
      },
      {
        type: "text",
        content: "Total: ",
        style: { bold: true }
      },
      {
        type: "dynamic",
        field: "{total}"
      },
      {
        type: "feed",
        lines: 2
      },
      {
        type: "qrcode",
        data: "https://byteburgers.com"
      },
      {
        type: "feed",
        lines: 2
      },
      {
        type: "text",
        content: "Thank you for your visit!",
        style: { size: "SMALL" }
      }
    ]
  }, null, 2);
  
  // JSON editing state - start with custom JSON showing the example
  const [useCustomJson, setUseCustomJson] = useState(true);
  const [customJson, setCustomJson] = useState(DEFAULT_PREVIEW_JSON);
  const [productionJson, setProductionJson] = useState(jsonDsl);
  const [jsonError, setJsonError] = useState<string | null>(null);
  
  // Order editing state - enable by default so template variables work
  const [orderJson, setOrderJson] = useState(JSON.stringify(DEFAULT_ORDER, null, 2));
  const [orderError, setOrderError] = useState<string | null>(null);
  const [useOrder, setUseOrder] = useState(true);
  
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const printerRef = useRef<EpsonPrinter | null>(null);

  // Define renderReceipt before the useEffects that use it
  const renderReceipt = useCallback(async () => {
    if (!printerRef.current || !canvasRef.current) return;
    
    setIsRendering(true);
    setError(null);

    try {
      // Clear the canvas
      if ('clear' in printerRef.current) {
        (printerRef.current as any).clear();
      }

      // Get the JSON to use
      const jsonToUse = useCustomJson ? customJson : productionJson;
      
      // Parse order if enabled
      let orderToUse = null;
      if (useOrder) {
        try {
          orderToUse = JSON.parse(orderJson);
        } catch (e) {
          throw new Error('Invalid Order JSON: ' + (e instanceof Error ? e.message : 'Unknown error'));
        }
      }

      // Execute the JavaScript interpreter
      await executeJavaScriptInterpreter(
        jsCode,
        jsonToUse,
        printerRef.current,
        orderToUse
      );
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to render receipt';
      setError(errorMessage);
      console.error('Receipt rendering error:', err);
    } finally {
      setIsRendering(false);
    }
  }, [useCustomJson, customJson, productionJson, jsCode, useOrder, orderJson]);

  // Update production JSON when it changes from parent (Design tab)
  useEffect(() => {
    setProductionJson(jsonDsl);
  }, [jsonDsl]);

  // Initialize printer and render when switching to receipt tab
  useEffect(() => {
    if (activeSubTab === 'receipt' && canvasRef.current) {
      // Always create a new printer instance when switching to receipt tab
      printerRef.current = new HTMLCanvasEpsonPrinter(canvasRef.current);
      // Render immediately after creating printer
      setTimeout(() => renderReceipt(), 100);
    }
  }, [activeSubTab, renderReceipt]);

  // Render receipt when JSON/code changes while on receipt tab
  useEffect(() => {
    if (activeSubTab === 'receipt' && canvasRef.current && printerRef.current) {
      renderReceipt();
    }
  }, [activeSubTab, renderReceipt]);

  const handleRefresh = () => {
    renderReceipt();
  };

  return (
    <div className="h-full flex flex-col p-6">
      <div className="flex-1 bg-gray-800 rounded-lg shadow-2xl flex flex-col overflow-hidden">
        {/* Header with sub-tabs */}
        <div className="border-b border-gray-700 flex-shrink-0">
          <div className="px-6 pt-4">
            <h2 className="text-xl font-bold text-gray-100">Receipt Preview</h2>
          </div>
          <div className="flex space-x-4 px-6 mt-3 overflow-x-auto">
            <button
              onClick={() => setActiveSubTab('json')}
              className={`pb-3 px-1 border-b-2 font-medium text-sm transition-colors whitespace-nowrap ${
                activeSubTab === 'json'
                  ? 'border-blue-400 text-blue-400'
                  : 'border-transparent text-gray-400 hover:text-gray-200'
              }`}
            >
              📝 JSON
            </button>
            <button
              onClick={() => setActiveSubTab('order')}
              className={`pb-3 px-1 border-b-2 font-medium text-sm transition-colors whitespace-nowrap ${
                activeSubTab === 'order'
                  ? 'border-blue-400 text-blue-400'
                  : 'border-transparent text-gray-400 hover:text-gray-200'
              }`}
            >
              🛒 Order
            </button>
            <button
              onClick={() => setActiveSubTab('api')}
              className={`pb-3 px-1 border-b-2 font-medium text-sm transition-colors whitespace-nowrap ${
                activeSubTab === 'api'
                  ? 'border-blue-400 text-blue-400'
                  : 'border-transparent text-gray-400 hover:text-gray-200'
              }`}
            >
              📖 Printer API
            </button>
            <button
              onClick={() => setActiveSubTab('interpreter')}
              className={`pb-3 px-1 border-b-2 font-medium text-sm transition-colors whitespace-nowrap ${
                activeSubTab === 'interpreter'
                  ? 'border-blue-400 text-blue-400'
                  : 'border-transparent text-gray-400 hover:text-gray-200'
              }`}
            >
              🔧 JS Interpreter
            </button>
            <button
              onClick={() => setActiveSubTab('receipt')}
              className={`pb-3 px-1 border-b-2 font-medium text-sm transition-colors whitespace-nowrap ${
                activeSubTab === 'receipt'
                  ? 'border-blue-400 text-blue-400'
                  : 'border-transparent text-gray-400 hover:text-gray-200'
              }`}
            >
              📄 Receipt
            </button>
          </div>
        </div>

        {/* Content */}
        <div className="flex-1 p-6 min-h-0 overflow-hidden">
          {/* JSON Tab */}
          {activeSubTab === 'json' && (
            <div className="h-full flex flex-col overflow-hidden">
              <div className="mb-2 flex items-center justify-between flex-shrink-0">
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={useCustomJson}
                    onChange={(e) => setUseCustomJson(e.target.checked)}
                    className="rounded"
                  />
                  <span className="text-sm font-medium text-gray-300">Use Custom JSON</span>
                </label>
                {!useCustomJson && (
                  <span className="text-xs text-gray-400">Using production JSON from Design tab</span>
                )}
              </div>

              <div className="flex-1 min-h-0" style={{ overflow: 'hidden' }}>
                <SimpleJSEditor
                  value={useCustomJson ? customJson : productionJson}
                  onChange={(value) => {
                    if (useCustomJson) {
                      setCustomJson(value);
                      // Validate JSON
                      try {
                        JSON.parse(value);
                        setJsonError(null);
                      } catch (e) {
                        setJsonError(e instanceof Error ? e.message : 'Invalid JSON');
                      }
                    }
                  }}
                  height="100%"
                  readOnly={!useCustomJson}
                />
              </div>

              {jsonError && (
                <div className="mt-2 p-2 bg-red-900 border border-red-700 rounded text-xs text-red-200 flex-shrink-0">
                  JSON Error: {jsonError}
                </div>
              )}

              <div className="mt-2 p-2 bg-gray-700 rounded-lg flex-shrink-0">
                <details className="cursor-pointer">
                  <summary className="text-xs text-gray-300 font-semibold">JSON DSL Format Guide</summary>
                  <pre className="text-xs text-gray-400 mt-2">
{`{
  "elements": [
    // Text with styling
    { "type": "text", "content": "STORE NAME", "style": { "bold": true, "size": "XLARGE" } },
    
    // Dynamic fields (resolved from order data)
    { "type": "dynamic", "field": "{store_name}" },
    { "type": "dynamic", "field": "{timestamp}" },
    { "type": "dynamic", "field": "{item_list}" },
    { "type": "dynamic", "field": "{total}" },
    
    // Layout elements
    { "type": "divider" },
    { "type": "feed", "lines": 2 },
    
    // Barcodes and QR codes
    { "type": "barcode", "data": "123456789", "barcodeType": "CODE39" },
    { "type": "qrcode", "data": "https://example.com" },
    
    // Images (base64)
    { "type": "image", "imageData": "base64_data_here" }
  ]
}

// Available dynamic fields:
// {store_name}, {store_address}, {store_number}
// {cashier_name}, {timestamp}, {order_number}
// {subtotal}, {tax}, {total}, {item_list}
// {customer_name}, {payment_method}, etc.`}
                  </pre>
                </details>
              </div>
            </div>
          )}

          {/* Order Tab */}
          {activeSubTab === 'order' && (
            <div className="h-full flex flex-col overflow-hidden">
              <div className="mb-2 flex items-center justify-between flex-shrink-0">
                <label className="flex items-center gap-2">
                  <input
                    type="checkbox"
                    checked={useOrder}
                    onChange={(e) => setUseOrder(e.target.checked)}
                    className="rounded"
                  />
                  <span className="text-sm font-medium text-gray-300">Include Order in Interpreter</span>
                </label>
                {useOrder && (
                  <button
                    onClick={() => setOrderJson(JSON.stringify(DEFAULT_ORDER, null, 2))}
                    className="px-3 py-1 text-xs bg-gray-700 hover:bg-gray-600 text-gray-300 rounded-lg transition-colors"
                  >
                    Reset to Default
                  </button>
                )}
              </div>

              <div className="flex-1 min-h-0" style={{ overflow: 'hidden' }}>
                <SimpleJSEditor
                  value={orderJson}
                  onChange={(value) => {
                    setOrderJson(value);
                    // Validate JSON
                    try {
                      JSON.parse(value);
                      setOrderError(null);
                    } catch (e) {
                      setOrderError(e instanceof Error ? e.message : 'Invalid JSON');
                    }
                  }}
                  height="100%"
                  readOnly={!useOrder}
                />
              </div>

              {orderError && (
                <div className="mt-2 p-2 bg-red-900 border border-red-700 rounded text-xs text-red-200 flex-shrink-0">
                  Order JSON Error: {orderError}
                </div>
              )}

              <div className="mt-2 p-2 bg-gray-700 rounded-lg flex-shrink-0">
                <details className="cursor-pointer">
                  <summary className="text-xs text-gray-300 font-semibold">Full Order Schema (click to expand)</summary>
                  <pre className="text-xs text-gray-400 mt-2 overflow-x-auto">
{`// Basic fields (Round 1+)
{
  "orderId": "A-0042",
  "storeNumber": "001",
  "storeName": "BYTE BURGERS",
  "timestamp": 1710123456789,
  
  "items": [{
    "name": "Cheeseburger",
    "quantity": 2,
    "unitPrice": 8.99,
    "totalPrice": 17.98,
    "sku?": "BURG-001",
    "category?": "BURGERS",
    "modifiers?": ["Medium Rare", "Extra Cheese"]
  }],
  
  "subtotal": 27.95,
  "taxRate": 0.08,
  "taxAmount": 2.24,
  "totalAmount": 30.19,
  
  // Round 2+ Promotions
  "itemPromotions?": [{
    "itemSku": "COFF-002",
    "promotionName": "Buy One Get One 50% Off",
    "discountAmount": 3.00
  }],
  "orderPromotions?": [{
    "promotionName": "Morning Rush Special",
    "discountAmount": 2.00,
    "promotionType": "PERCENTAGE" | "FIXED"
  }],
  
  // Round 3+ Customer
  "customerInfo?": {
    "customerId": "CUST-8826",
    "name": "John Doe",
    "memberStatus?": "GOLD",
    "loyaltyPoints?": 1247,
    "memberSince?": "2019-03-15"
  },
  "paymentMethod?": "VISA ****1234",
  
  // Round 5+ Split Payment
  "splitPayments?": [{
    "payerName": "Alice Chen",
    "amount": 156.43,
    "method": "VISA ****7823",
    "tip?": 25.00,
    "items?": ["Wagyu Steak", "Truffle Fries"]
  }],
  "tableInfo?": {
    "tableNumber": "12",
    "serverName": "Jennifer K.",
    "guestCount": 3,
    "serviceRating?": 5
  }
}`}
                  </pre>
                </details>
              </div>
            </div>
          )}

          {activeSubTab === 'receipt' && (
            <div className="h-full flex flex-col overflow-hidden">
              {/* Error display */}
              {error && (
                <div className="mb-2 p-2 bg-red-900 border border-red-700 rounded-lg flex-shrink-0">
                  <h3 className="font-semibold text-red-200 text-sm">Error</h3>
                  <pre className="text-xs text-red-300 whitespace-pre-wrap font-mono">{error}</pre>
                </div>
              )}

              {/* Refresh button and status */}
              <div className="mb-2 flex items-center justify-between flex-shrink-0">
                <div className="flex items-center gap-4">
                  <button
                    onClick={handleRefresh}
                    disabled={isRendering}
                    className={`px-3 py-1 rounded-lg font-medium text-sm transition-all ${
                      isRendering
                        ? 'bg-gray-700 text-gray-500 cursor-not-allowed'
                        : 'bg-blue-600 text-white hover:bg-blue-700'
                    }`}
                  >
                    {isRendering ? '🔄 Rendering...' : '🔄 Refresh Preview'}
                  </button>
                  {isRendering && (
                    <span className="text-xs text-gray-400">Processing interpreter...</span>
                  )}
                </div>
                <div className="text-xs text-gray-400 space-x-3">
                  <span>JSON: {useCustomJson ? '✏️ Custom' : '📝 Production'}</span>
                  <span>Order: {useOrder ? '✅ Included' : '❌ None'}</span>
                </div>
              </div>

              {/* Canvas container */}
              <div className="flex-1 min-h-0 overflow-auto bg-gray-900 rounded-lg p-4">
                <div className="flex justify-center">
                  <div
                    style={{
                      background: 'white',
                      borderRadius: '12px',
                      boxShadow: '0 4px 24px rgba(0,0,0,0.15)',
                      padding: '20px',
                      width: 'fit-content'
                    }}
                  >
                    <canvas
                      ref={canvasRef}
                      width={480}
                      height={2000}
                      style={{
                        display: 'block',
                        background: 'white',
                        borderRadius: '8px'
                      }}
                    />
                  </div>
                </div>
              </div>

              {/* Current JSON display */}
              <div className="mt-2 flex-shrink-0">
                <details className="cursor-pointer bg-gray-900 rounded-lg p-2">
                  <summary className="text-xs font-medium text-gray-300">
                    Current JSON DSL (click to expand)
                  </summary>
                  <pre className="mt-2 text-xs bg-black text-green-400 p-2 rounded overflow-x-auto max-h-32 font-mono">
                    {useCustomJson ? customJson : productionJson || '// No JSON generated yet - design a receipt first!'}
                  </pre>
                </details>
              </div>
            </div>
          )}

          {activeSubTab === 'interpreter' && (
            <div className="h-full flex flex-col overflow-hidden">
              <div className="mb-2 flex-shrink-0">
                <div className="flex items-center justify-between">
                  <label className="block text-sm font-medium text-gray-300">
                    JavaScript Interpreter Code
                    <span className="ml-2 text-xs text-gray-500">
                      (function interpret(jsonString, printer, order) {})
                    </span>
                  </label>
                  <button
                    onClick={() => setJsCode(DEFAULT_JS_INTERPRETER)}
                    className="px-3 py-1 text-xs bg-gray-700 hover:bg-gray-600 text-gray-300 rounded-lg transition-colors"
                  >
                    Reset to Default
                  </button>
                </div>
              </div>

              <div className="flex-1 min-h-0" style={{ overflow: 'hidden' }}>
                <SimpleJSEditor
                  value={jsCode}
                  onChange={setJsCode}
                  height="100%"
                />
              </div>

              <div className="mt-2 flex-shrink-0">
                <details className="cursor-pointer bg-gray-700 border border-gray-600 rounded-lg p-2">
                  <summary className="text-xs text-gray-300 font-semibold">Enhanced JS Interpreter Tips (click to expand)</summary>
                  <div className="text-xs text-gray-400 space-y-2 mt-2">
                    <div className="bg-gray-800 p-2 rounded">
                      <p className="font-semibold text-gray-300">Function Signature:</p>
                      <code className="text-green-400">function interpret(jsonString, printer, order)</code>
                      <ul className="list-disc list-inside space-y-1 mt-1">
                        <li><strong>jsonString:</strong> JSON DSL from Visual Receipt Designer</li>
                        <li><strong>printer:</strong> EpsonPrinter interface with methods like addText(), addQRCode()</li>
                        <li><strong>order:</strong> Order data object (null if not provided)</li>
                      </ul>
                    </div>
                    
                    <div className="bg-gray-800 p-2 rounded">
                      <p className="font-semibold text-gray-300">JSON DSL Elements to Handle:</p>
                      <ul className="list-disc list-inside space-y-1">
                        <li><strong>text:</strong> Static text with optional styling</li>
                        <li><strong>dynamic:</strong> Dynamic fields resolved from order data</li>
                        <li><strong>divider:</strong> Horizontal line separators</li>
                        <li><strong>feed:</strong> Blank lines for spacing</li>
                        <li><strong>barcode:</strong> Various barcode types</li>
                        <li><strong>qrcode:</strong> QR codes with data and options</li>
                        <li><strong>image:</strong> Base64 encoded images</li>
                      </ul>
                    </div>
                    
                    <div className="bg-gray-800 p-2 rounded">
                      <p className="font-semibold text-gray-300">Dynamic Field Resolution:</p>
                      <ul className="list-disc list-inside space-y-1">
                        <li>Handle fields like {'{store_name}'}, {'{timestamp}'}, {'{total}'}</li>
                        <li>Use order data when available, fallback to defaults</li>
                        <li>Format currency properly: ${'{order.totalAmount.toFixed(2)}'}</li>
                        <li>Format item lists with quantities and prices</li>
                      </ul>
                    </div>
                    
                    <div className="bg-blue-900 bg-opacity-30 border border-blue-700 rounded p-2">
                      <p className="font-semibold text-blue-300">💡 Key Points:</p>
                      <ul className="list-disc list-inside space-y-1">
                        <li>Always call printer.cutPaper() at the end</li>
                        <li>Use try-catch for error handling</li>
                        <li>This matches the Kotlin interpreter you'll submit</li>
                        <li>Test with both JSON DSL and Order data enabled</li>
                        <li>Preview updates automatically when you switch tabs</li>
                      </ul>
                    </div>
                  </div>
                </details>
              </div>
            </div>
          )}

          {activeSubTab === 'api' && (
            <div className="h-full overflow-auto">
              <div className="max-w-4xl mx-auto space-y-6">
                <div className="bg-gray-900 rounded-lg p-4">
                  <h3 className="text-lg font-bold text-blue-400 mb-3">🖨️ EpsonPrinter API Reference</h3>
                  <p className="text-sm text-gray-300 mb-4">
                    Complete reference for all methods and constants available in your interpreter function.
                  </p>
                </div>

                {/* Core Methods */}
                <div className="bg-gray-900 rounded-lg p-4">
                  <h4 className="text-md font-bold text-green-400 mb-3">Core Printing Methods</h4>
                  <div className="space-y-3">
                    <div className="bg-black rounded p-3">
                      <code className="text-blue-300">printer.addText(text: string, style?: TextStyle)</code>
                      <p className="text-xs text-gray-400 mt-1">Prints text with optional styling</p>
                      <pre className="text-xs text-green-400 mt-2">
{`// Examples
printer.addText("Hello World");
printer.addText("Bold Text", { bold: true });
printer.addText("Large Text", { bold: true, underline: true, size: 'LARGE' });`}
                      </pre>
                    </div>

                    <div className="bg-black rounded p-3">
                      <code className="text-blue-300">printer.addTextAlign(alignment: Alignment)</code>
                      <p className="text-xs text-gray-400 mt-1">Sets text alignment for subsequent text</p>
                      <pre className="text-xs text-green-400 mt-2">
{`// Alignment enum: LEFT, CENTER, RIGHT
printer.addTextAlign('CENTER');
printer.addText("Centered Text");
printer.addTextAlign('LEFT'); // Reset to left`}
                      </pre>
                    </div>

                    <div className="bg-black rounded p-3">
                      <code className="text-blue-300">printer.addTextStyle(style: TextStyle)</code>
                      <p className="text-xs text-gray-400 mt-1">Sets text style for subsequent text</p>
                      <pre className="text-xs text-green-400 mt-2">
{`printer.addTextStyle({ bold: true, underline: false, size: 'LARGE' });
printer.addText("Styled Text");
printer.addTextStyle({ size: 'NORMAL' }); // Reset`}
                      </pre>
                    </div>

                    <div className="bg-black rounded p-3">
                      <code className="text-blue-300">printer.addFeedLine(lines: number)</code>
                      <p className="text-xs text-gray-400 mt-1">Feeds blank lines (adds vertical spacing)</p>
                      <pre className="text-xs text-green-400 mt-2">
{`printer.addFeedLine(2); // Add 2 blank lines`}
                      </pre>
                    </div>

                    <div className="bg-black rounded p-3">
                      <code className="text-blue-300">printer.cutPaper()</code>
                      <p className="text-xs text-gray-400 mt-1">Cuts the paper (marks end of receipt)</p>
                      <pre className="text-xs text-green-400 mt-2">
{`printer.addFeedLine(3);
printer.cutPaper(); // Always call at the end`}
                      </pre>
                    </div>
                  </div>
                </div>

                {/* Advanced Methods */}
                <div className="bg-gray-900 rounded-lg p-4">
                  <h4 className="text-md font-bold text-green-400 mb-3">Advanced Methods</h4>
                  <div className="space-y-3">
                    <div className="bg-black rounded p-3">
                      <code className="text-blue-300">printer.addQRCode(data: string, options?: QRCodeOptions)</code>
                      <p className="text-xs text-gray-400 mt-1">Prints a QR code</p>
                      <pre className="text-xs text-green-400 mt-2">
{`printer.addQRCode("https://example.com");
printer.addQRCode("WIFI:T:WPA;S:MyNetwork;P:MyPassword;;", {
  size: 3, // Size multiplier (1-16)
  errorCorrection: 'H' // L, M, Q, or H
});`}
                      </pre>
                    </div>

                    <div className="bg-black rounded p-3">
                      <code className="text-blue-300">printer.addBarcode(data: string, type: BarcodeType, options?: BarcodeOptions)</code>
                      <p className="text-xs text-gray-400 mt-1">Prints various types of barcodes</p>
                      <pre className="text-xs text-green-400 mt-2">
{`// BarcodeType: CODE128, CODE39, EAN13, UPC_A, etc.
printer.addBarcode("123456789", "CODE128");
printer.addBarcode("ABC123", "CODE39", {
  width: 'MEDIUM', // THIN, MEDIUM, THICK
  height: 50,
  hri: true // Human Readable Interpretation
});`}
                      </pre>
                    </div>

                    <div className="bg-black rounded p-3">
                      <code className="text-blue-300">printer.addTextStyle(style: TextStyle)</code>
                      <p className="text-xs text-gray-400 mt-1">Sets default text style for subsequent text</p>
                      <pre className="text-xs text-green-400 mt-2">
{`printer.addTextStyle({ bold: true, underline: true });
printer.addText("This will be bold and underlined");
printer.addTextStyle({}); // Reset styles`}
                      </pre>
                    </div>

                    <div className="bg-black rounded p-3">
                      <code className="text-blue-300">printer.addLineSpace(space: number)</code>
                      <p className="text-xs text-gray-400 mt-1">Sets line spacing in pixels (default: 30)</p>
                      <pre className="text-xs text-green-400 mt-2">
{`printer.addLineSpace(50); // Increase line spacing
printer.addText("Spaced text");`}
                      </pre>
                    </div>

                    <div className="bg-black rounded p-3">
                      <code className="text-blue-300">printer.clear()</code>
                      <p className="text-xs text-gray-400 mt-1">Clears the canvas (preview only)</p>
                      <pre className="text-xs text-green-400 mt-2">
{`printer.clear(); // Start fresh`}
                      </pre>
                    </div>
                  </div>
                </div>

                {/* Type Definitions */}
                <div className="bg-gray-900 rounded-lg p-4">
                  <h4 className="text-md font-bold text-green-400 mb-3">Type Definitions & Options</h4>
                  <div className="space-y-3">
                    <div className="bg-black rounded p-3">
                      <code className="text-yellow-300">TextStyle</code>
                      <pre className="text-xs text-gray-300 mt-2">
{`interface TextStyle {
  bold?: boolean;
  underline?: boolean;
  size?: TextSize; // SMALL, NORMAL, LARGE, XLARGE
}

enum TextSize {
  SMALL = 'SMALL',
  NORMAL = 'NORMAL',
  LARGE = 'LARGE',
  XLARGE = 'XLARGE'
}`}
                      </pre>
                    </div>

                    <div className="bg-black rounded p-3">
                      <code className="text-yellow-300">BarcodeType</code>
                      <pre className="text-xs text-gray-300 mt-2">
{`enum BarcodeType {
  UPC_A, UPC_E, EAN13, EAN8,
  CODE39, ITF, CODABAR, CODE93, CODE128,
  GS1_128, GS1_DATABAR_OMNIDIRECTIONAL,
  GS1_DATABAR_TRUNCATED, GS1_DATABAR_LIMITED,
  GS1_DATABAR_EXPANDED
}`}
                      </pre>
                    </div>

                    <div className="bg-black rounded p-3">
                      <code className="text-yellow-300">QRCodeOptions</code>
                      <pre className="text-xs text-gray-300 mt-2">
{`interface QRCodeOptions {
  size?: number;  // Size multiplier (default: 3)
  errorCorrection?: QRErrorCorrection; // L, M, Q, H (default: M)
}

enum QRErrorCorrection {
  L = 'L', M = 'M', Q = 'Q', H = 'H'
}`}
                      </pre>
                    </div>

                    <div className="bg-black rounded p-3">
                      <code className="text-yellow-300">BarcodeOptions & Alignment</code>
                      <pre className="text-xs text-gray-300 mt-2">
{`interface BarcodeOptions {
  width?: BarcodeWidth;  // THIN, MEDIUM, THICK (default: MEDIUM)
  height?: number;  // Height in pixels (default: 50)
  hri?: boolean;  // Human Readable Interpretation (default: true)
}

enum Alignment {
  LEFT = 'LEFT',
  CENTER = 'CENTER',
  RIGHT = 'RIGHT'
}`}
                      </pre>
                    </div>

                  </div>
                </div>

                {/* Complete Example */}
                <div className="bg-gray-900 rounded-lg p-4">
                  <h4 className="text-md font-bold text-green-400 mb-3">Complete Example</h4>
                  <div className="bg-black rounded p-3">
                    <pre className="text-xs text-green-400 overflow-x-auto">
{`function interpret(jsonString, printer, order) {
  const json = JSON.parse(jsonString);
  
  // Header
  printer.addTextAlign('CENTER');
  printer.addText(json.storeName || "STORE NAME", { 
    bold: true, 
    size: 'XLARGE' 
  });
  printer.addFeedLine(1);
  
  // Date/Time
  printer.addText(new Date().toLocaleString());
  printer.addFeedLine(2);
  
  // Items (if order provided)
  if (order) {
    printer.addTextAlign('LEFT');
    printer.addText("ORDER #" + order.orderId);
    printer.addFeedLine(1);
    
    order.items.forEach(item => {
      const line = item.name.padEnd(20) + " $" + item.totalPrice.toFixed(2);
      printer.addText(line);
    });
    
    printer.addFeedLine(1);
    printer.addTextAlign('RIGHT');
    printer.addText("TOTAL: $" + order.totalAmount.toFixed(2), { 
      bold: true,
      size: 'LARGE'
    });
  }
  
  // QR Code
  printer.addFeedLine(2);
  printer.addTextAlign('CENTER');
  printer.addQRCode("https://payment.example.com/order/" + (order?.orderId || "test"), {
    size: 3,
    errorCorrection: 'H'
  });
  
  // Footer
  printer.addFeedLine(1);
  printer.addText("Thank you for your business!");
  printer.addFeedLine(3);
  printer.cutPaper();
}`}
                    </pre>
                  </div>
                </div>

                {/* Tips */}
                <div className="bg-blue-900 bg-opacity-30 border border-blue-700 rounded-lg p-4">
                  <h4 className="text-md font-bold text-blue-400 mb-2">💡 Pro Tips</h4>
                  <ul className="text-xs text-gray-300 space-y-1 list-disc list-inside">
                    <li>Always call <code className="text-green-400">printer.cutPaper()</code> at the end</li>
                    <li>Reset text size with <code className="text-green-400">printer.addTextSize(1, 1)</code> after making text larger</li>
                    <li>Use <code className="text-green-400">printer.addFeedLine()</code> for spacing instead of adding empty text</li>
                    <li>Text alignment affects all subsequent text until changed</li>
                    <li>For Kotlin: Replace <code className="text-green-400">printer.</code> with <code className="text-green-400">printer.</code> (same API)</li>
                    <li>In Kotlin, use string templates: <code className="text-green-400">{'"Total: $${amount}"'}</code></li>
                  </ul>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ReceiptPreview;